[".claude/nikiforovall"]
type = "git-repo"
url = "https://github.com/NikiforovAll/private-claude"
refreshPeriod = "1h"

[".claude/claude-code-rules"]
type = "git-repo"
url = "https://github.com/NikiforovAll/claude-code-rules"
refreshPeriod = "1h"

[".config/opencode/nikiforovall"]
type = "git-repo"
url = "https://github.com/NikiforovAll/private-opencode"
refreshPeriod = "1h"
