[merge]
command = "pwsh"
args = ["-NoProfile", "-Command", "Copy-Item '{{ .Target }}' '{{ .Target }}.base'; code --new-window --wait --merge '{{ .Destination }}' '{{ .Target }}' '{{ .Target }}.base' '{{ .Source }}'"]

[interpreters.ps1]
command = "pwsh"
args = ["-NoProfile", "-Command", "[Console]::In.ReadToEnd() | pwsh -NoProfile -File $args[0]"]
