
[terminal]
shell = { program = "C:/Program Files/Git/bin/bash.exe", args = ["--login", "-i"] }

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 1.0
padding = { x = 20, y = 20 }
dynamic_padding = true

[font]
size = 12.0
[font.normal]
family = "MesloLGM Nerd Font"

# Gruvbox Dark
[colors.primary]
background = "#282828"
foreground = "#EBDBB2"

[general]
working_directory = "C:/Users/nikiforovall/dev"
