
[terminal]
shell = { program = "C:/Program Files/Git/bin/bash.exe", args = [
    "--login",
    "-i",
] }

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 1.0
padding = { x = 5, y = 5 }
dynamic_padding = true

[mouse]
hide_when_typing = true

[font]
size = 12.0
[font.normal]
family = "MesloLGM Nerd Font"

[general]
working_directory = "C:/Users/nikiforovall/dev"
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[keyboard]
bindings = [
    { key = 'PageUp', mods = "Shift", action = 'ScrollPageUp' },
    { key = 'PageDown', mods = "Shift", action = 'ScrollPageDown' },
    { key = 'PageUp', mods = "Control", action = 'ScrollToTop' },
    { key = 'PageDown', mods = "Control", action = 'ScrollToBottom' },
]
